# Generated by Django 3.2.5 on 2021-08-12 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_travelpost_bullets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpost',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='travel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.travelpost')),
            ],
        ),
    ]
