# Generated by Django 3.2.5 on 2021-08-14 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210814_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comments',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.somepost'),
        ),
        migrations.AddField(
            model_name='blogpostcomment',
            name='replies',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.somepost'),
        ),
        migrations.AlterField(
            model_name='blogpostcomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.somepost'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.somepost'),
        ),
    ]
