# Generated by Django 3.2.5 on 2021-08-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('api', '0010_auto_20210814_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='comments',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.somepost'),
        ),
        migrations.AddField(
            model_name='travelpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
