#!/bin/bash

NAME="myblog"
DIR=/home/sk/myblog/myblog
USER=sk
GROUP=sk
WORKERS=3
BIND=unix:/home/sk/myblog/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=myblog.settings
DJANGO_WSGI_MODULE=myblog.wsgi
LOG_LEVEL=error

cd $DIR
source ../pass/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../pass/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-